spring:
  application:
  name: springbootshedlockExample
  datasource:
    url: jdbc:postgresql://localhost/test
    driverClassName: org.postgresql.Driver
    username: test123
    password: test
    platform: org.hibernate.dialect.Postgresql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml

#Scehduler time
schedule:
  time: "0 0/1 * * * ?"
  #Shedlock config
  lock:
    atmost: 5m
    atleast: 2m
